name: GitHub Actions Demo

on:
  [pull_request]
  # types: [review_requested]

jobs:
  Example-GitHub-Action-Name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - run: npm install

      - name: Cypress run
        uses: cypress-io/github-action@v2
